name: Docker Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR Public
        id: login-ecr
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m7w0w0j5
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker image
        run: docker build -t devops_lekce6 .

      - name: Tag Docker image
        run: docker tag devops_lekce6:latest public.ecr.aws/m7w0w0j5/devops_lekce6:latest

      - name: Push Docker image to Amazon ECR Public
        run: docker push public.ecr.aws/m7w0w0j5/devops_lekce6:latest
